model:
  gaussian:
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 1.6e-6
          max_steps: 30_000
        scales_lr: 0.001
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      depth_normalized: true
      depth_loss_weight:
        init: 1.0
        final_factor: 0.1
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
      depth_ratio: 1.0
      diable_trimming: true
  density: 
    class_path: internal.density_controllers.citygsv2_density_controller.CityGSV2DensityController
    init_args:
      densification_interval: 1000
      opacity_reset_interval: 20000
      densify_from_iter: 4000
      densify_grad_threshold: 0.00005
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  path: data/matrix_city/street/train/block_A
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 1
      depth_scale_lower_bound: 0.01
      depth_scale_upper_bound: 50.0