model:
  initialize_from: outputs/citygsv2_smbu_coarse_sh2_t1/checkpoints/epoch=60-step=30000.ckpt
  overwrite_config: False
  gaussian:
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_init: 0.000064
        means_lr_scheduler:
          lr_final: 0.00000064
        scales_lr: 0.004
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      normal_regularization_from_iter: 0
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.05
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
      depth_ratio: 1.0
      prune_ratio: 0.05
  density: internal.density_controllers.citygsv2_density_controller.CityGSV2DensityController
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  path: data/GauU_Scene/SMBU
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 3.4175
      content_threshold: 0.05
      block_dim:  # removed z dimension
      - 3
      - 3